version: '3.8'

services:
  tumor-detection:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
      - ./config.json:/app/config.json
    environment:
      - PYTHONPATH=/app
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add a database service for production
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: tumor_detection
      POSTGRES_USER: tumor_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - production

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    profiles:
      - production

volumes:
  postgres_data:
